"""remove_session_id

Revision ID: f81e43bcf9f7
Revises: 5dc465522eb8
Create Date: 2026-01-17 22:28:59.912546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81e43bcf9f7'
down_revision: Union[str, None] = '5dc465522eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_session_id', table_name='chunks')
    op.drop_constraint('chunks_session_id_fkey', 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'session_id')
    op.drop_index('ix_documents_session_id', table_name='documents')
    op.drop_constraint('documents_session_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'session_id')
    op.drop_index('idx_embeddings_vector_ivfflat', table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_embeddings_session_id', table_name='embeddings')
    op.drop_constraint('embeddings_session_id_fkey', 'embeddings', type_='foreignkey')
    op.drop_column('embeddings', 'session_id')
    
    # Recreate the vector similarity index (CRITICAL for performance)
    op.execute('''
        CREATE INDEX idx_embeddings_vector_ivfflat 
        ON embeddings 
        USING ivfflat (embedding vector_cosine_ops) 
        WITH (lists = 100);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('embeddings_session_id_fkey', 'embeddings', 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index('ix_embeddings_session_id', 'embeddings', ['session_id'], unique=False)
    op.create_index('idx_embeddings_vector_ivfflat', 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('documents', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_session_id_fkey', 'documents', 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index('ix_documents_session_id', 'documents', ['session_id'], unique=False)
    op.add_column('chunks', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('chunks_session_id_fkey', 'chunks', 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.create_index('ix_chunks_session_id', 'chunks', ['session_id'], unique=False)
    # ### end Alembic commands ###