"""add_collections_table

Revision ID: 6ebaf1ec46e2
Revises: f81e43bcf9f7
Create Date: 2026-01-17 22:57:03.475606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebaf1ec46e2'
down_revision: Union[str, None] = 'f81e43bcf9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create collections table first
    op.create_table('collections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    
    # Create a default collection for existing documents
    op.execute("""
        INSERT INTO collections (id, name, description)
        VALUES (gen_random_uuid(), 'default', 'Default collection for existing documents')
    """)
    
    # Add collection_id column to documents
    op.add_column('documents', sa.Column('collection_id', sa.UUID(), nullable=True))
    
    # Set all existing documents to the default collection
    op.execute("""
        UPDATE documents
        SET collection_id = (SELECT id FROM collections WHERE name = 'default')
    """)
    
    # Now make collection_id NOT NULL
    op.alter_column('documents', 'collection_id', nullable=False)
    
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_foreign_key('documents_collection_id_fkey', 'documents', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_collection_id_fkey', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.drop_column('documents', 'collection_id')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###