"""add pgvector support and embeddings tables

Revision ID: 5dc465522eb8
Revises: 96c6ad85e6be
Create Date: 2026-01-17 20:46:33.227751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc465522eb8'
down_revision: Union[str, None] = '96c6ad85e6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension exists
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    # Fix chat_sessions constraints BEFORE creating new tables
    # Drop the existing foreign key constraint from chat_messages
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    
    # Now we can safely drop and recreate the unique constraint
    op.drop_constraint('chat_sessions_session_id_key', 'chat_sessions', type_='unique')
    op.drop_index('ix_chat_sessions_session_id', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    
    # Recreate the foreign key constraint with the new index
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    
    # Make session_id NOT NULL on chat_messages
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_session_id'), 'chunks', ['session_id'], unique=False)
    
    # Create embeddings table with vector type using raw SQL
    # This avoids the Vector() type from pgvector.sqlalchemy which requires extension at import time
    op.execute('''
        CREATE TABLE embeddings (
            id UUID NOT NULL PRIMARY KEY,
            chunk_id UUID NOT NULL,
            document_id UUID NOT NULL,
            session_id UUID NOT NULL,
            embedding vector(1536) NOT NULL,
            embedding_model VARCHAR(100),
            text_preview TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            FOREIGN KEY(chunk_id) REFERENCES chunks (id) ON DELETE CASCADE,
            FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE,
            FOREIGN KEY(session_id) REFERENCES chat_sessions (session_id) ON DELETE CASCADE
        );
    ''')
    
    # Create indexes for the embeddings table
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_embeddings_document_id'), 'embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_embeddings_session_id'), 'embeddings', ['session_id'], unique=False)
    
    # Create vector similarity index for pgvector (CRITICAL for performance)
    op.execute('''
        CREATE INDEX idx_embeddings_vector_ivfflat 
        ON embeddings 
        USING ivfflat (embedding vector_cosine_ops) 
        WITH (lists = 100);
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.create_index('ix_chat_sessions_session_id', 'chat_sessions', ['session_id'], unique=False)
    op.create_unique_constraint('chat_sessions_session_id_key', 'chat_sessions', ['session_id'])
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Drop vector index first
    op.execute('DROP INDEX IF EXISTS idx_embeddings_vector_ivfflat;')
    
    op.drop_index(op.f('ix_embeddings_session_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_document_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_chunks_session_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###